version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .  # Caminho onde está o Dockerfile
      dockerfile: Dockerfile  # Nome do Dockerfile (se não for o padrão)
    ports:
      - "3030:3030"
    volumes:
      - .:/usr/src/helena_paixao_backend  # Para desenvolvimento
    environment:
      NODE_ENV: production  # Adicione outras variáveis de ambiente conforme necessário
    command: npm run serve

volumes:
  db_data:
